-- Migration : table products
CREATE TABLE IF NOT EXISTS products (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL UNIQUE,
    description TEXT DEFAULT NULL,
    short_description VARCHAR(500) DEFAULT NULL,
    price DECIMAL(8,2) NOT NULL,
    sale_price DECIMAL(8,2) DEFAULT NULL,
    sku VARCHAR(50) DEFAULT NULL UNIQUE,
    stock INT NOT NULL DEFAULT 0,
    weight DECIMAL(6,2) DEFAULT NULL,
    volume VARCHAR(50) DEFAULT NULL,
    alcohol_percentage DECIMAL(4,1) DEFAULT NULL,
    category VARCHAR(100) DEFAULT NULL,
    image_id INT UNSIGNED DEFAULT NULL,
    gallery TEXT DEFAULT NULL COMMENT 'JSON array of media IDs',
    meta_title VARCHAR(255) DEFAULT NULL,
    meta_description VARCHAR(500) DEFAULT NULL,
    is_featured TINYINT(1) NOT NULL DEFAULT 0,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    sort_order INT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_slug (slug),
    INDEX idx_category (category),
    INDEX idx_featured (is_featured),
    INDEX idx_active (is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
